baseurl: /pokemon
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: 'post'
github:
  issues_url: https://github.com/mal/pokemon/issues
  repository_url: https://github.com/mal/pokemon
sass:
  sass_dir: assets/_sass
